global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sender_app"
    metrics_path: "/actuator/prometheus"
    # Override global settings
    scrape_interval: 5s

    static_configs:
      - targets: ["micro-sender:8083","micro-collector:8084","micro-recipient:8085"]